version: 0.2
phases:
  install:
    runtime-versions:
      java: 8
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:      
      - . cicd/variables.sh
      - ./gradlew clean assemble testDebugUnitTestCoverage coveralls
artifacts:
  discard-paths: yes
  files:
    - "**/*.apk"
cache:
  paths:
    - "/root/.gradle/caches"